version: '2.2'
services:
    sharelatex:
        restart: always
        image: robol/overleaf_ldap
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
        privileged: false
        ports:
            - 80:80
            # - 40000:40000 # For Node debug
        links:
            - mongo
            - redis
        volumes:
            - ./sharelatex:/var/lib/sharelatex
        networks:
            - backend
        environment:
            SHARELATEX_APP_NAME: Overleaf UniPi
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
            ADMIN_MAIL: admin@unipi.it
            DOMAIN: unipi.it
            LDAP_SERVER: ldap://idmauth.unipi.it
            LDAP_SERVER_DM: ldaps://student.dm.unipi.it
            LDAP_DOMAINS: "unipi.it,studenti.unipi.it,mail.dm.unipi.it"

            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            # DEBUG_NODE: "true"

            # This is currently needed to avoid verification in 
            # development. 
            NODE_TLS_REJECT_UNAUTHORIZED: "0"

            ENABLED_LINKED_FILE_TYPES: 'url,project_file'

            # Enables Thumbnail generation using ImageMagick
            ENABLE_CONVERSIONS: 'true'

            # Disables email confirmation requirement
            EMAIL_CONFIRMATION_DISABLED: 'true'

            # temporary fix for LuaLaTex compiles
            # see https://github.com/overleaf/overleaf/issues/695
            TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var

            SHARELATEX_SITE_URL: https://tex.cs.dm.unipi.it
            SHARELATEX_NAV_TITLE: Overleaf @ DM UniPi
            # SHARELATEX_HEADER_IMAGE_URL: http://somewhere.com/mylogo.png
            SHARELATEX_ADMIN_EMAIL: help@dm.unipi.it

            SHARELATEX_LEFT_FOOTER: '[{"text": "Powered by <a href=\"https://overleaf.com\">Overleaf</a> 2020"},{"text": "Hosted by <a href=\"https://www.dm.unipi.it/\">Department of Mathematics</a>, University of Pisa"} ]'
            # SHARELATEX_RIGHT_FOOTER: '[{"text": "Hello I am on the Right"} ]'

    mongo:
        restart: always
        image: mongo
        ports:
            - 27017
        volumes:
            - ./mongo:/data/db
        networks:
            - backend
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5

    redis:
        restart: always
        image: redis:5
        ports:
            - 6379
        volumes:
            - ./redis:/data
        networks:
            - backend

networks:
  backend:
